# Generated by Django 2.2.1 on 2020-07-15 16:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintsubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sprintsubscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sprintsubscription',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='sprintsubscription',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
