# Generated by Django 2.2.1 on 2020-07-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_subscriptions', '0002_auto_20200715_1646'),
        ('att_subscriptions', '0002_auto_20200715_1646'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateTimeField(null=True)),
                ('data_used', models.IntegerField()),
                ('usage_type', models.CharField(choices=[('data', 'Data'), ('voice', 'Voice')], max_length=10)),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
        migrations.RemoveField(
            model_name='voiceusagerecord',
            name='att_subscription_id',
        ),
        migrations.RemoveField(
            model_name='voiceusagerecord',
            name='sprint_subscription_id',
        ),
        migrations.DeleteModel(
            name='DataUsageRecord',
        ),
        migrations.DeleteModel(
            name='VoiceUsageRecord',
        ),
    ]
